// create new router
const ejs = require("ejs");
const express = require("express");
const router = express.Router();

const redirectLogin = (req, res, next) => {
    if (!req.session.userId ) {
        res.redirect('../users/login') // redirect to the login page
    } else {
        next (); // move to the next middleware function
    } 
}

router.get('/general',function(req, res, next){ 
    // link to page with preview of timer and calendar or prompt to sign up to use calendar
    res.render("tools.ejs")
});

router.get('/calendar', redirectLogin, function(req, res, next){
    res.render("calendar.ejs")
    // view of calendar with prompt to sign in?
});

// view personal calendar
router.get('/calendar/events', redirectLogin, function(req, res, next){
    const userId = req.session.userId;
    const sqlQuery = 'SELECT title, start, end, description FROM calendar WHERE user_id = ?';

    db.query(sqlQuery, [userId], (err, result) => {
        if(err) {
            next(err);
            return;
        };

        // send FullCalendar an array of data
        const events = result.map(event => ({ 
            // create array "events" by mapping database query results onto key-value pairs
            id: event.id,
            title: event.title,
            start: event.start,
            end: event.end,
            description: event.description
        }));

        res.json(events); // send JSON array

        // res.send(`found calendar event: ${result}`);
    });

    // res.render("calendar.ejs")
    // redirect to login if not signed in
});

// add event to calendar
router.post('/calendar/events', redirectLogin, function(req, res, next){
    const userId = req.session.userId;
    const title = req.body.title;
    const start =  req.body.start;
    const end = req.body.end;
    const description = req.body.description;

    const sqlQuery = 'INSERT INTO calendar (user_id, title, start, end, description) VALUES (?,?,?,?,?)';

    db.query(sqlQuery, [userId, title, start, end, description], (err, result) => {
        if(err) {
            next(err);
            return;
        };

        res.json({message: `added calendar event: ${result}`});

        // res.json({
        //     eventId: result.insertId, // the id generated by auto_increment
        //     title,
        //     start,
        //     end,
        //     description
        // });
    });

    // res.render("calendar.ejs");
    // redirect to login if not signed in
});

// delete event from calendar
router.delete('/calendar/events/:id', redirectLogin, function(req, res, next){
    res.render("calendar.ejs")
    // redirect to login if not signed in
});

router.get('/timer', function (req, res, next) {
    res.render("timer.ejs");
});

router.get('/mytimer', redirectLogin, function(req, res, next) {
    // login required, show users saved time preferences
});

// -- add timer preferences for individual users - new page or injected into timer.ejs?

// Export the router object so index.js can access it
module.exports = router;